export const BUY_MOBILE_APPEL = "BUY_MOBILE_APPEL";
export const BUY_MOBILE_SAMSUNG = "BUY_MOBILE_SAMSUNG";
export const BUY_TABLET_SAMSUNG = "BUY_TABLET_SAMSUNG";
export const BUY_TABLET_IPAD = "BUY_TABLET_SAMSUNG";